controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
app_evenement_index:
    path: /evenement
    controller: App\Controller\EvenementController::front
    methods: GET

app_evenement_participate:
    path: /evenement/participate/{id}
    controller: App\Controller\EvenementController::participate
    methods: GET


app_participation_list:
    path: /participation
    controller: App\Controller\ParticipationController::index
    methods: GET

# config/routes.yaml
app_panier:
    path: /panier
    controller: App\Controller\EvenementController::viewPanier

app_panier_add:
  path: /panier/add/{id}
  controller: App\Controller\EvenementController::addToPanier
  methods: [GET]
app_evenement_show:
    path: /evenement/{id}
    controller: App\Controller\EvenementController::show


app_panier_show:
    path: /panier
    controller: App\Controller\PanierController::showPanier

app_panier_remove:
    path: /panier/remove/{id}
    controller: App\Controller\PanierController::removeFromPanier


