controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
app_evenement_index:
    path: /evenement
    controller: App\Controller\EvenementController::front
    methods: GET

app_evenement_participate:
    path: /evenement/participate/{id}
    controller: App\Controller\EvenementController::participate
    methods: GET


app_participation_list:
    path: /participation
    controller: App\Controller\ParticipationController::index
    methods: GET